[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spark-data-lake-demo"
version = "0.0.1"

dependencies = [
  'pyspark'
]

[project.optional-dependencies]
tests = [
  'pytest==7.3.1',
]
