name: Build website

on:
  workflow_call:

jobs:
  build-docs:
    name: Build docs website
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: website
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build
