name: Check pull request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "website/**"

jobs:
  build:
    uses: ./.github/workflows/_build.yml
