name: Run e2e tests

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: "(Optional) PR Number. If you specify a value here, the value of the branch field will be ignored."
        required: false
        default: ""

env:
  NODE_VERSION: 20

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
      PR_NUMBER: ${{ inputs.prNumber }}
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: write
    strategy:
        matrix:
          suite: [processing, storage, governance, utils, consumption, streaming]
        fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      # If we pass a PR Number when triggering the workflow we will retrieve the PR info and get its headSHA
      - name: Extract PR details
        id: extract_PR_details
        if: ${{ inputs.prNumber != '' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const script = require('.github/scripts/get-pr-info.js');
            await script({github, context, core});
      # Only if a PR Number was passed and the headSHA of the PR extracted,
      # we checkout the PR at that point in time
      - name: Checkout PR code
        if: ${{ inputs.prNumber != '' }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          ref: ${{ steps.extract_PR_details.outputs.headSHA }}
      - name: Setup NodeJS and dependency cache
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock
            framework/yarn.lock
            solutions/yarn.lock
      - name: Install dependencies
        run: yarn install --check-files --frozen-lockfile
      - name: Build
        run: npx projen build
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
          aws-region: eu-west-1
          role-duration-seconds: 10800
      - name: Run e2e tests
        run: cd framework && npx jest --group=e2e/${{ matrix.suite }}